### PR TITLE
Coding Convention and Django presentation

### PR DESCRIPTION
**Pull request by amisha2016**

### CODE REVIEW

**Comment by mandeeps708** [comment]
Don't add so much commits for a single thing. It should be in a single commit.

**Comment by mandeeps708** [comment]
@amisha2016 
See output and make changes: http://greatdevelopers.github.io/Coding_Convention/

**Comment by mandeeps708** [comment]
Also figure out why your post "2016-06-22-Apache_vs_Nginx.markdown" doesn't appear on the website.

**Comment by amisha2016** [comment]
On Wed, Jun 22, 2016 at 8:35 PM, Mandeep Singh notifications@github.com
wrote:

> Also figure out why your post "2016-06-22-Apache_vs_Nginx.markdown"
> doesn't appear on the website
> 
> ​I have not pulled it yet.
> ​

## 

Regards,
Amisha Budhiraja.
Blog: https://amisha2016.wordpress.com
Gitlab: https://gitlab.com/u/Amisha2016

**Comment by mandeeps708** [comment]
Don't know what do you mean by pulled here. It is in the wrong folder not in the _posts directory.

**Pull request merged**
