### PR TITLE
libxdfrw_library

### PR DESCRIPTION
**Pull request by Gagandeepkaur123**

### CODE REVIEW

**Comment by mandeeps708** [comment]
Why you sent two files in this PR?
It is supposed to be one.
I guess the startup one was already added.

**Comment by Gagandeepkaur123** [comment]
On Thu, Jul 7, 2016 at 10:53 PM, Mandeep Singh notifications@github.com wrote:

> Why you sent two files in this PR?
> It is supposed to be one.
> I guess the startup one was already added.
> 
> Yes, I only pulled c++ library report. But this got also attached. I
> did some mistake. I don't know how this one attatched.
> What is the way that old one's will not be visible again.

## 

## 

Regards
Gagandeep Kaur

Blog:https://gagan95.wordpress.com/
Github:https://github.com/gagandeepkaur123
Gitlab:http://gitlab.com/gagandeep

**Comment by mandeeps708** [comment]
First of all, you have to keep your local repository in sync with the remote repository. Do `git status` much often.

And "pulled" is not the right word. It should be "pushed" instead.

I am closing this PR (Pull Request) and expecting you to make changes and send a single file.

Thank you.

**Comment by Gagandeepkaur123** [comment]
On Thu, Jul 7, 2016 at 11:24 PM, Gagandeep Kaur gk1995127@gmail.com wrote:

> On Thu, Jul 7, 2016 at 11:19 PM, Mandeep Singh notifications@github.com wrote:
> 
> > Ok. I will do.
> 
> ## Please check. I pushed it again.
> 
> ## 
> 
> Regards
> Gagandeep Kaur
> 
> Blog:https://gagan95.wordpress.com/
> Github:https://github.com/gagandeepkaur123
> Gitlab:http://gitlab.com/gagandeep

## 

## 

Regards
Gagandeep Kaur

Blog:https://gagan95.wordpress.com/
Github:https://github.com/gagandeepkaur123
Gitlab:http://gitlab.com/gagandeep

**Pull request closed without merging**
